name = input("hello there, what is your name? ")
print(f"Okay {name} if you are ready for some  amazing jokes just press enter")
input()
print("Hello are you ready for some very good jokes")
input()
print("Great well here you go, why did the chicken cross the road")
input()
print("because it had just gone to the grocery store and needed to go home")
input()
print("okay that might not have been very good but this one has to be better")
input()
print("Right....")
input()
print("knock knock")
input()
print(f"tom from the irs you need to pay your taxes {name}")
input()
print("knock knock")
input()
print("tom again if you dont open up we will sent a swat team")
input()
print("swat squad open up")
input()
print("*bang")
print("go go go")
print("get him")
print("I swear I paid my taxes")
input()
print(f"why did {name} go to prison")
input()
print("jaywalking")